
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "rgstpbaljoamkhjhomzp"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns in a single REST request.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# The maximum number of connections the pooler can use.
pool_size = 20
# Only attempt to use the connection pooler for the following users
default_pool_size = 20
pool_mode = "transaction"
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"
# External URL of the functions server that frontend connects to.
functions_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

# Use pre-defined map of phone number to OTP for testing.
[auth.sms.test_otp]
# 4152127777 = "123456"

# Configure one of the supported SMS providers: twilio, messagebird, textlocal, vonage.
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
# message_service_sid or from is required
from = ""
auth_token = ""

# Use custom SMTP server for sending emails.
[auth.smtp]
enabled = false
# From address for emails sent from your app
sender_name = ""
sender_email = ""
host = ""
port = 25
user = ""
password = ""
# Can be 'plain', 'ssl', 'tls', 'starttls'. Default is 'plain'.
method = "plain"
# Sender address for recovery emails, defaults to sender_email
# recovery_email = ""

# Configure one of the supported OAuth providers.
[auth.external.apple]
enabled = false
client_id = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-apple#generating-a-client_secret
secret_key = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-apple#generating-a-client_secret
team_id = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-apple#generating-a-client_secret
key_id = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-apple#adding-custom-scopes
scope = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-azure#adding-custom-scopes
scope = ""
# Refer to https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent
auth_url = ""
token_url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-bitbucket#adding-custom-scopes
scope = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-discord#adding-custom-scopes
scope = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-facebook#adding-custom-scopes
scope = ""
# Leave empty to use the default. Comma-separated parameters, such as auth_type=reauthenticate
queries = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-github#adding-custom-scopes
scope = ""
# Refer to https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-gitlab#adding-custom-scopes
scope = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-google#adding-custom-scopes
scope = ""
# Get from https://cloud.google.com/identity-platform/docs/reference/oidc-parameters#google
queries = ""

[auth.external.kakao]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-keycloak#configuration
base_url = ""
realm = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-keycloak#adding-custom-scopes
scope = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-linkedin#adding-custom-scopes
scope = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-notion#adding-custom-scopes
scope = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-twitch#adding-custom-scopes
scope = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
# To use Twitter v2 OAuth, need to set it to '2.0'. Otherwise, defaults to v1.1 OAuth
version = "1.1"

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-slack#configuration
base_url = "https://slack.com/openid/connect"
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-slack#adding-custom-scopes
scope = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-spotify#adding-custom-scopes
scope = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
# Get from https://workos.com/docs/reference/organization-auth#client-side-sdk-initialization
base_url = "https://api.workos.com/"
# Get from https://workos.com/docs/reference/organization-auth#client-side-sdk-initialization
authority_id = ""
# These are used to authenticate user's Organization: add multiple entries for each allowed Domain
# domains = ["supabase.com", "acme.com"]
# These are used to authenticate user's Organization: add multiple entries for each allowed Organization ID
# organization_ids = ["org_124"]
# Choose to authenticate users via SSO or MagicAuth
[auth.external.workos.sso]
enabled = false
# Get from https://workos.com/docs/reference/sso/authorize#client-side
scope = "sso:read"
# Get from https://workos.com/docs/reference/sso/authorize#client-side
connection = ""
# Get from https://workos.com/docs/reference/sso/authorize#client-side
provider = ""

[auth.external.workos.magicauth]
enabled = false

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
# Refer to https://docs.supabase.com/guides/auth/social-login/auth-zoom#adding-custom-scopes
scope = ""

[auth.external.vk]
enabled = false
client_id = ""
secret = ""
scope = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Optional: Disable default page_view instrumentation.
disable_page_view_instrumentation = false
# Optional: Backend API URL. This can be set to an external analytics service.
backend_url = "http://localhost:54327"
gzip_compression = false

[experimental]
# This feature allows you to debug the internals of the Local Development setup by generating an edge
# runtime at development time. Note that this is experimental and should not be used in production!
enable_debug_runtime = false

[edge_functions]
[edge_functions.send-notification]
verify_jwt = false

[edge_functions.send-onboarding-email]
verify_jwt = false

[edge_functions.create-onboarding-tables]
verify_jwt = false
