
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgstpbaljoamkhjhomzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnc3RwYmFsam9hbWtoamhvbXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjYxMzMsImV4cCI6MjA2MTM0MjEzM30.DLpKUaIo0REcRQzCAYV1bxW2bqqIdHNcsgBYf9SNRuE";

// Get the current domain or use scrollcourt.xyz as default
const getCurrentSiteUrl = () => {
  // In browser environment
  if (typeof window !== 'undefined') {
    return window.location.origin;
  }
  // Default to scrollcourt.xyz
  return "https://scrollcourt.xyz";
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storage: localStorage,
    // Use site URL from the current domain
    site_url: getCurrentSiteUrl()
  }
});

// Export helper to check if Supabase is properly configured
export const isSupabaseConfigured = () => {
  return !!SUPABASE_URL && !!SUPABASE_PUBLISHABLE_KEY;
};
